from __future__ import annotations

import os

from agenthub.adapters.base import AgentResult, AgentTask
from agenthub.domain.run import RunContext
from agenthub.adapters.openai_chat.client import OpenAICompatibleProvider
from agenthub.runtime.prompt_builder import format_messages_for_prompt


class CodexAdapter:
    def __init__(
        self,
        agent_id: str = "codex",
        name: str | None = None,
        capabilities: list[str] | None = None,
        skills: list[str] | None = None,
        model: str = "mock",
        api_key: str | None = None,
        base_url: str | None = None,
    ) -> None:
        self.id = agent_id
        self.name = name or "Codex"
        self.capabilities = capabilities or ["code", "review", "refactor"]
        self.skills = skills or []
        resolved_model = model if model and model != "mock" else os.environ.get("CODEX_MODEL", model)
        self.model = resolved_model
        self.provider = OpenAICompatibleProvider(
            model=resolved_model,
            api_key=api_key,
            base_url=base_url,
        )

    def run(self, task: AgentTask, context: RunContext) -> AgentResult:
        default_mode = "llm" if os.environ.get("ENABLE_REAL_LLM", "").lower() in {"1", "true", "yes", "on"} else "mock"
        mode = os.environ.get("CODEX_MODE", default_mode).strip().lower()
        if mode in {"llm", "openai", "openai_chat"}:
            return self._run_with_openai_compatible(task, context)
        return self._run_mock(task, context)

    def _run_mock(self, task: AgentTask, context: RunContext) -> AgentResult:
        content = (
            "Codex received the coding task and produced a draft implementation plan.\n\n"
            "```tsx\n"
            "export default function GeneratedByCodex() {\n"
            "  return <section>Generated by Codex</section>;\n"
            "}\n"
            "```"
        )
        return AgentResult(
            agent_id=self.id,
            messages=[
                {
                    "role": "agent",
                    "sender": self.id,
                    "content": content,
                    "format": "markdown",
                }
            ],
            artifacts=[
                {
                    "id": "codex_code",
                    "type": "code",
                    "title": "GeneratedByCodex.tsx",
                    "language": "tsx",
                    "file_path": "GeneratedByCodex.tsx",
                    "content": (
                        f"// task: {task.instruction}\n"
                        "export default function GeneratedByCodex() {\n"
                        "  return <section>Generated by Codex</section>;\n"
                        "}\n"
                    ),
                }
            ],
        )

    def _run_with_openai_compatible(
        self,
        task: AgentTask,
        context: RunContext,
    ) -> AgentResult:
        prompt = self._build_prompt(task, context)
        try:
            if any(
                str(attachment.get("mime_type", "")).startswith("image/")
                for attachment in context.attachments or []
            ):
                content = self.provider.complete_with_attachments(prompt, context.attachments or [])
            else:
                content = self.provider.complete(prompt)
        except Exception as exc:
            return AgentResult(
                agent_id=self.id,
                status="error",
                messages=[
                    {
                        "role": "agent",
                        "sender": self.id,
                        "content": f"Codex adapter failed: {exc}",
                        "format": "markdown",
                    }
                ],
                error=str(exc),
            )

        return AgentResult(
            agent_id=self.id,
            messages=[
                {
                    "role": "agent",
                    "sender": self.id,
                    "content": content,
                    "format": "markdown",
                }
            ],
            artifacts=[
                {
                    "id": "codex_code",
                    "type": "code",
                    "title": "CodexOutput.tsx",
                    "language": "tsx",
                    "file_path": "CodexOutput.tsx",
                    "content": content,
                }
            ],
        )

    def _build_prompt(self, task: AgentTask, context: RunContext) -> str:
        history = format_messages_for_prompt(context.history, limit=8, total_limit=4200)
        skill_text = "\n\n".join(self.skills) if self.skills else "No extra skills configured."
        return (
            f"You are {self.name}, a coding agent inside AgentHub.\n"
            f"Conversation mode: {context.mode}\n"
            f"Available tools requested by orchestrator: {', '.join(task.tools) or 'none'}\n"
            f"Skills:\n{skill_text}\n\n"
            f"Pinned long-term context:\n{self._format_pinned_context(context)}\n\n"
            f"LLM memories:\n{self._format_memories(context)}\n\n"
            f"Conversation summary:\n{self._format_summary(context)}\n\n"
            f"Current attachments:\n{self._format_attachments(context)}\n\n"
            f"Recent history:\n{history}\n\n"
            f"Task:\n{task.instruction}\n\n"
            "Return concise markdown. Use fenced code blocks for code."
        )

    def _format_pinned_context(self, context: RunContext) -> str:
        return format_messages_for_prompt(
            context.pinned_context,
            limit=8,
            item_limit=700,
            total_limit=2400,
            empty="No pinned context.",
        )

    def _format_memories(self, context: RunContext) -> str:
        if not context.conversation_memories:
            return "No long-term memories."
        lines = []
        for memory in context.conversation_memories:
            category = str(memory.get("category") or "memory")
            content = str(memory.get("content") or "").strip()
            if content:
                lines.append(f"- [{category}] {content}")
        return "\n".join(lines) if lines else "No long-term memories."

    def _format_summary(self, context: RunContext) -> str:
        if not context.conversation_summary:
            return "No long-context summary."
        return str(context.conversation_summary.get("content") or "No long-context summary.")

    def _format_attachments(self, context: RunContext) -> str:
        if not context.attachments:
            return "No attachments."
        sections: list[str] = []
        for attachment in context.attachments:
            extracted = str(attachment.get("extracted_text") or "").strip()
            preview = extracted[:3000] if extracted else "No extracted text."
            sections.append(
                f"- {attachment.get('filename')} ({attachment.get('mime_type')}):\n{preview}"
            )
        return "\n\n".join(sections)
