from __future__ import annotations

import os

from agenthub_harness.adapters.base import AgentResult, AgentTask
from agenthub_harness.core.context import RunContext
from agenthub_harness.llm.openai_compatible_provider import OpenAICompatibleProvider


class CodexAdapter:
    def __init__(
        self,
        agent_id: str = "codex",
        name: str | None = None,
        capabilities: list[str] | None = None,
        skills: list[str] | None = None,
        model: str = "mock",
    ) -> None:
        self.id = agent_id
        self.name = name or "Codex"
        self.capabilities = capabilities or ["code", "review", "refactor"]
        self.skills = skills or []
        self.model = model
        self.provider = OpenAICompatibleProvider(model=os.environ.get("CODEX_MODEL", model))

    def run(self, task: AgentTask, context: RunContext) -> AgentResult:
        mode = os.environ.get("CODEX_MODE", "mock").strip().lower()
        if mode in {"llm", "openai", "openai_chat"}:
            return self._run_with_openai_compatible(task, context)
        return self._run_mock(task, context)

    def _run_mock(self, task: AgentTask, context: RunContext) -> AgentResult:
        content = (
            "Codex received the coding task and produced a draft implementation plan.\n\n"
            "```tsx\n"
            "export default function GeneratedByCodex() {\n"
            "  return <section>Generated by Codex</section>;\n"
            "}\n"
            "```"
        )
        return AgentResult(
            agent_id=self.id,
            messages=[
                {
                    "role": "agent",
                    "sender": self.id,
                    "content": content,
                    "format": "markdown",
                }
            ],
            artifacts=[
                {
                    "id": "codex_code",
                    "type": "code",
                    "title": "GeneratedByCodex.tsx",
                    "language": "tsx",
                    "file_path": "GeneratedByCodex.tsx",
                    "content": (
                        f"// task: {task.instruction}\n"
                        "export default function GeneratedByCodex() {\n"
                        "  return <section>Generated by Codex</section>;\n"
                        "}\n"
                    ),
                }
            ],
        )

    def _run_with_openai_compatible(
        self,
        task: AgentTask,
        context: RunContext,
    ) -> AgentResult:
        prompt = self._build_prompt(task, context)
        try:
            content = self.provider.complete(prompt)
        except Exception as exc:
            return AgentResult(
                agent_id=self.id,
                status="error",
                messages=[
                    {
                        "role": "agent",
                        "sender": self.id,
                        "content": f"Codex adapter failed: {exc}",
                        "format": "markdown",
                    }
                ],
                error=str(exc),
            )

        return AgentResult(
            agent_id=self.id,
            messages=[
                {
                    "role": "agent",
                    "sender": self.id,
                    "content": content,
                    "format": "markdown",
                }
            ],
            artifacts=[
                {
                    "id": "codex_code",
                    "type": "code",
                    "title": "CodexOutput.tsx",
                    "language": "tsx",
                    "file_path": "CodexOutput.tsx",
                    "content": content,
                }
            ],
        )

    def _build_prompt(self, task: AgentTask, context: RunContext) -> str:
        history = "\n".join(
            f"{item.get('sender') or item.get('role')}: {item.get('content')}"
            for item in context.history[-8:]
        )
        skill_text = "\n\n".join(self.skills) if self.skills else "No extra skills configured."
        return (
            f"You are {self.name}, a coding agent inside AgentHub.\n"
            f"Conversation mode: {context.mode}\n"
            f"Available tools requested by orchestrator: {', '.join(task.tools) or 'none'}\n"
            f"Skills:\n{skill_text}\n\n"
            f"Recent history:\n{history}\n\n"
            f"Task:\n{task.instruction}\n\n"
            "Return concise markdown. Use fenced code blocks for code."
        )
