from __future__ import annotations

from html import escape
from pathlib import Path
from uuid import uuid4

from agenthub.tools.schemas import ToolResult


DEPLOYMENT_DIR = Path("agent-workspace/deployments")


def deploy_tool(
    title: str = "AgentHub Static Deployment",
    code: str = "",
    preview_html: str = "",
    **_: object,
) -> ToolResult:
    deployment_id = f"dep_{uuid4().hex[:12]}"
    target_dir = DEPLOYMENT_DIR / deployment_id
    target_dir.mkdir(parents=True, exist_ok=True)
    html = preview_html or _html_from_code(title, code)
    (target_dir / "index.html").write_text(html, encoding="utf-8")
    preview_url = f"/deployments/{deployment_id}/index.html"
    logs = (
        f"Deployment {deployment_id} completed.\n"
        f"Generated static preview at {preview_url}."
    )
    return ToolResult(
        id="deployment_result",
        type="deployment",
        title=title,
        content=logs,
        preview_url=preview_url,
        metadata={
            "deployment_id": deployment_id,
            "status": "success",
            "logs": logs,
            "deployment_url": preview_url,
        },
    )


def _html_from_code(title: str, code: str) -> str:
    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{escape(title)}</title>
    <style>
      body {{ font-family: Inter, system-ui, sans-serif; margin: 0; padding: 32px; background: #f8fafc; color: #0f172a; }}
      main {{ max-width: 860px; margin: 0 auto; background: #fff; border: 1px solid #e2e8f0; border-radius: 18px; padding: 24px; }}
      pre {{ white-space: pre-wrap; background: #0f172a; color: #e2e8f0; border-radius: 14px; padding: 16px; overflow: auto; }}
    </style>
  </head>
  <body>
    <main>
      <h1>{escape(title)}</h1>
      <p>This static deployment was generated by AgentHub.</p>
      <pre>{escape(code or "No source artifact was available.")}</pre>
    </main>
  </body>
</html>"""
