from agenthub_harness.tools.schemas import ToolResult


def preview_tool(title: str = "Todo List Preview", code: str = "") -> ToolResult:
    preview_html = f"""
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{title}</title>
    <style>
      body {{ font-family: Inter, system-ui, sans-serif; margin: 0; padding: 24px; background: #f7fafc; color: #172033; }}
      .card {{ max-width: 560px; border: 1px solid #d7e1ee; border-radius: 8px; padding: 20px; background: #fff; box-shadow: 0 10px 30px rgba(20, 34, 60, 0.08); }}
      pre {{ white-space: pre-wrap; background: #182536; color: #d8ecff; padding: 12px; border-radius: 8px; overflow: auto; }}
    </style>
  </head>
  <body>
    <main class="card">
      <h1>{title}</h1>
      <p>This preview was generated by AgentHub's preview tool.</p>
      <pre>{code}</pre>
    </main>
  </body>
</html>
"""
    return ToolResult(
        id="art_003",
        type="preview",
        title=title,
        content="/artifacts/art_003/preview",
        preview_url="/artifacts/art_003/preview",
        preview_html=preview_html,
    )
